export const copia = {
  app: 'Atendimentos',
  carregando: 'Abrindo a Base local neste aparelho…',
  loginTitulo: 'Entrar',
  identificacao: 'Identificação',
  senha: 'Senha',
  entrar: 'Entrar',
  esqueciASenha: 'Esqueci a senha',
  avisoBaseLocal:
    'A Base local vive neste aparelho. Nenhum e-mail e nenhum outro telefone recebe estes registros.',
  esqueciTitulo: 'Esqueci a senha',
  esqueciCorpo:
    'Não há recuperação por e-mail porque a Base local vive neste aparelho. Nenhum e-mail e nenhum outro telefone recebe esses dados.',
  voltarAoLogin: 'Voltar ao login',
  formularioTitulo: 'Anotar',
  formularioAba: 'Anotar',
  atendimentosTitulo: 'Atendimentos',
  atendimentosAba: 'Lista',
  atividadesTitulo: 'Atividades',
  atividadesAba: 'Atividades',
  avisoCatalogo:
    'Quem se reveza neste telefone vê o mesmo catálogo. Outro aparelho não recebe estes registros.',
  erroAtividades: 'Não foi possível carregar as Atividades neste aparelho.',
  atividadeVigente: 'Atividade vigente',
  atividade: 'Atividade',
  nome: 'Nome',
  obrigatoria: 'obrigatória',
  gravarAtendimento: 'Gravar Atendimento',
  erroSemAtividadeVigente: 'Escolha a Atividade vigente para gravar o Atendimento.',
  erroGravarAtendimento: 'Não foi possível gravar o Atendimento neste aparelho.',
  erroEscolherVigente: 'Não foi possível guardar a Atividade vigente neste aparelho.',
  listaVazia: 'Ainda não há Atendimento neste aparelho. Use o formulário para gravar o primeiro.',
  irAoFormulario: 'Ir ao formulário',
  semIdentificacao: 'Sem identificação',
  detalheTitulo: 'Atendimento',
  erroAtendimento: 'Não foi possível abrir este Atendimento.',
  erroLista: 'Não foi possível carregar os Atendimentos neste aparelho.',
  dataHora: 'Data e hora',
}
