export const copia = {
  app: 'Atendimentos',
  carregando: 'Abrindo a Base local neste aparelho…',
  loginTitulo: 'Entrar',
  identificacao: 'Identificação',
  senha: 'Senha',
  entrar: 'Entrar',
  esqueciASenha: 'Esqueci a senha',
  avisoBaseLocal:
    'A Base local vive neste aparelho. Nenhum e-mail e nenhum outro telefone recebe estes registros.',
  esqueciTitulo: 'Esqueci a senha',
  esqueciCorpo:
    'Não há recuperação por e-mail porque a Base local vive neste aparelho. Nenhum e-mail e nenhum outro telefone recebe esses dados.',
  voltarAoLogin: 'Voltar ao login',
  formularioTitulo: 'Anotar',
  formularioAba: 'Anotar',
  atendimentosTitulo: 'Atendimentos',
  atendimentosAba: 'Lista',
  atividadesTitulo: 'Atividades',
  atividadesAba: 'Atividades',
  avisoCatalogo:
    'Quem se reveza neste telefone vê o mesmo catálogo. Outro aparelho não recebe estes registros.',
  novaAtividade: 'Nova Atividade',
  criarAtividade: 'Criar Atividade',
  renomear: 'Renomear',
  guardarNome: 'Guardar nome',
  cancelar: 'Cancelar',
  apagar: 'Apagar',
  erroAtividades: 'Não foi possível carregar as Atividades neste aparelho.',
  erroCriarAtividade: 'Não foi possível criar a Atividade neste aparelho.',
  erroRenomearAtividade: 'Não foi possível renomear a Atividade neste aparelho.',
  erroApagarAtividade: 'Não foi possível apagar a Atividade neste aparelho.',
  atividadeVigente: 'Atividade vigente',
  atividade: 'Atividade',
  nome: 'Nome',
  obrigatoria: 'obrigatória',
  gravarAtendimento: 'Gravar Atendimento',
  erroSemAtividadeVigente: 'Escolha a Atividade vigente para gravar o Atendimento.',
  erroGravarAtendimento: 'Não foi possível gravar o Atendimento neste aparelho.',
  erroEscolherVigente: 'Não foi possível guardar a Atividade vigente neste aparelho.',
  listaVazia: 'Ainda não há Atendimento neste aparelho. Use o formulário para gravar o primeiro.',
  irAoFormulario: 'Ir ao formulário',
  semIdentificacao: 'Sem identificação',
  detalheTitulo: 'Atendimento',
  erroAtendimento: 'Não foi possível abrir este Atendimento.',
  erroLista: 'Não foi possível carregar os Atendimentos neste aparelho.',
  dataHora: 'Data e hora',
  opcional: 'opcional',
  cpf: 'CPF',
  dataNascimento: 'Data de nascimento',
  racaCor: 'Raça/cor',
  escolaridade: 'Escolaridade',
  faixaRenda: 'Faixa de renda',
  cidade: 'Cidade',
  bairro: 'Bairro',
  situacaoRua: 'Situação de rua',
  usoSubstancias: 'Uso de substâncias',
  dataDoAtendimento: 'Data do atendimento',
  informativoIdentificacao:
    'Falta de identificação única distorce qualquer leitura como se fosse “pessoas”. Vários Atendimentos da mesma pessoa — com ou sem CPF — também distorcem essa leitura.',
  novoAtendimento: 'Novo atendimento',
  atendimentoGravado: 'Atendimento gravado neste aparelho.',
  naoInformado: 'Não informado',
  graficosTitulo: 'Gráficos',
  graficosAba: 'Gráficos',
  todasAtividades: 'Todas as Atividades',
  filtroAtividade: 'Filtrar por Atividade',
  faixaEtaria: 'Faixa etária',
  graficosVazio:
    'Ainda não há Atendimento neste recorte neste aparelho. Os gráficos aparecem quando houver pelo menos uma linha.',
  erroGraficos: 'Não foi possível carregar os Indicadores neste aparelho.',
}
